<B>Passengers (All Carriers - All Airports )</B><BR><table class="dataTDRight" cellspacing="1" cellpadding="4" rules="all" border="1" id="DataGrid1" style="width:750px;">
	<tr class="libraryTHY2_Center" style="color:White;background-color:#5D95C9;">
		<td>Year</td><td>Month</td><td>DOMESTIC</td><td>INTERNATIONAL</td><td>TOTAL</td>
	</tr><tr class="dataTDRight">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2002</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">10</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">48,054,917</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">9,578,435</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">57,633,352</td>
	</tr><tr class="dataTDRight" style="background-color:#EFEFEF;">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2002</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">11</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">44,850,246</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">9,016,535</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">53,866,781</td>
	</tr><tr class="dataTDRight">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2002</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">12</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">49,684,353</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">10,038,794</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">59,723,147</td>
	</tr><tr class="dataTDRight" style="background-color:LightYellow;">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;"><B>2002</B></td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;"><B>TOTAL</B></td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;"><B>551,899,643</B></td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;"><B>118,704,850</B></td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;"><B>670,604,493</B></td>
	</tr><tr class="dataTDRight">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2003</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">1</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">43,032,450</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">9,726,436</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">52,758,886</td>
	</tr><tr class="dataTDRight" style="background-color:#EFEFEF;">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2003</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">41,166,780</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">8,283,372</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">49,450,152</td>
	</tr><tr class="dataTDRight">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2003</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">3</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">49,992,700</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">9,538,653</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">59,531,353</td>
	</tr><tr class="dataTDRight" style="background-color:#EFEFEF;">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2003</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">4</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">47,033,260</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">8,309,305</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">55,342,565</td>
	</tr><tr class="dataTDRight">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2003</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">5</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">49,152,352</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">8,801,873</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">57,954,225</td>
	</tr><tr class="dataTDRight" style="background-color:#EFEFEF;">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2003</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">6</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">52,209,516</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">10,347,900</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">62,557,416</td>
	</tr><tr class="dataTDRight">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2003</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">7</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">55,810,773</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">11,705,206</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">67,515,979</td>
	</tr><tr class="dataTDRight" style="background-color:#EFEFEF;">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2003</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">8</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">53,920,973</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">11,799,672</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">65,720,645</td>
	</tr><tr class="dataTDRight">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2003</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">9</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">44,213,408</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">9,454,647</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">53,668,055</td>
	</tr><tr class="dataTDRight" style="background-color:#EFEFEF;">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2003</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">10</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">49,944,935</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">9,608,358</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">59,553,293</td>
	</tr><tr class="dataTDRight">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2003</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">11</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">47,059,495</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">9,481,886</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">56,541,381</td>
	</tr><tr class="dataTDRight" style="background-color:#EFEFEF;">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2003</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">12</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">49,757,124</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">10,512,547</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">60,269,671</td>
	</tr><tr class="dataTDRight" style="background-color:LightYellow;">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;"><B>2003</B></td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;"><B>TOTAL</B></td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;"><B>583,293,766</B></td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;"><B>117,569,855</B></td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;"><B>700,863,621</B></td>
	</tr><tr class="dataTDRight" style="background-color:#EFEFEF;">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2004</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">1</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">43,815,481</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">10,252,443</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">54,067,924</td>
	</tr><tr class="dataTDRight">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2004</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">45,306,644</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">9,310,317</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">54,616,961</td>
	</tr><tr class="dataTDRight" style="background-color:#EFEFEF;">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2004</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">3</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">54,147,227</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">10,976,440</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">65,123,667</td>
	</tr><tr class="dataTDRight">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2004</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">4</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">53,253,194</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">10,802,022</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">64,055,216</td>
	</tr><tr class="dataTDRight" style="background-color:#EFEFEF;">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2004</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">5</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">53,030,873</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">10,971,254</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">64,002,127</td>
	</tr><tr class="dataTDRight">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2004</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">6</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">56,959,142</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">12,159,514</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">69,118,656</td>
	</tr><tr class="dataTDRight" style="background-color:#EFEFEF;">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2004</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">7</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">59,614,287</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">13,502,913</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">73,117,200</td>
	</tr><tr class="dataTDRight">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2004</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">8</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">57,380,873</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">13,203,566</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">70,584,439</td>
	</tr><tr class="dataTDRight" style="background-color:#EFEFEF;">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2004</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">9</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">47,671,785</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">10,570,682</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">58,242,467</td>
	</tr><tr class="dataTDRight">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2004</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">10</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">54,167,489</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">10,772,177</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">64,939,666</td>
	</tr><tr class="dataTDRight" style="background-color:#EFEFEF;">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2004</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">11</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">51,782,564</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">10,174,320</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">61,956,884</td>
	</tr><tr class="dataTDRight">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2004</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">12</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">52,640,057</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">11,244,427</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">63,884,484</td>
	</tr><tr class="dataTDRight" style="background-color:LightYellow;">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;"><B>2004</B></td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;"><B>TOTAL</B></td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;"><B>629,769,616</B></td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;"><B>133,940,075</B></td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;"><B>763,709,691</B></td>
	</tr><tr class="dataTDRight">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2005</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">1</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">47,977,657</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">11,387,275</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">59,364,932</td>
	</tr><tr class="dataTDRight" style="background-color:#EFEFEF;">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2005</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">47,074,882</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">9,945,067</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">57,019,949</td>
	</tr><tr class="dataTDRight">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2005</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">3</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">58,838,975</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">12,479,643</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">71,318,618</td>
	</tr><tr class="dataTDRight" style="background-color:#EFEFEF;">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2005</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">4</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">54,908,859</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">11,521,174</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">66,430,033</td>
	</tr><tr class="dataTDRight">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2005</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">5</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">57,323,876</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">12,164,600</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">69,488,476</td>
	</tr><tr class="dataTDRight" style="background-color:#EFEFEF;">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2005</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">6</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">59,724,061</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">13,140,061</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">72,864,122</td>
	</tr><tr class="dataTDRight">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2005</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">7</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">62,396,446</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">14,421,209</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">76,817,655</td>
	</tr><tr class="dataTDRight" style="background-color:#EFEFEF;">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2005</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">8</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">59,110,633</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">13,703,334</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">72,813,967</td>
	</tr><tr class="dataTDRight">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2005</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">9</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">50,600,325</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">11,325,800</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">61,926,125</td>
	</tr><tr class="dataTDRight" style="background-color:#EFEFEF;">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2005</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">10</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">53,738,093</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">11,107,586</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">64,845,679</td>
	</tr><tr class="dataTDRight">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2005</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">11</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">52,766,404</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">10,580,099</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">63,346,503</td>
	</tr><tr class="dataTDRight" style="background-color:#EFEFEF;">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2005</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">12</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">52,801,276</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">11,812,574</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">64,613,850</td>
	</tr><tr class="dataTDRight" style="background-color:LightYellow;">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;"><B>2005</B></td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;"><B>TOTAL</B></td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;"><B>657,261,487</B></td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;"><B>143,588,422</B></td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;"><B>800,849,909</B></td>
	</tr><tr class="dataTDRight" style="background-color:#EFEFEF;">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2006</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">1</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">48,886,043</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">11,724,098</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">60,610,141</td>
	</tr><tr class="dataTDRight">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2006</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">47,348,142</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">10,167,275</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">57,515,417</td>
	</tr><tr class="dataTDRight" style="background-color:#EFEFEF;">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2006</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">3</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">58,286,011</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">12,707,241</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">70,993,252</td>
	</tr><tr class="dataTDRight">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2006</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">4</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">55,828,555</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">12,619,137</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">68,447,692</td>
	</tr><tr class="dataTDRight" style="background-color:#EFEFEF;">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2006</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">5</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">57,145,193</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">12,610,793</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">69,755,986</td>
	</tr><tr class="dataTDRight">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2006</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">6</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">59,297,121</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">13,690,835</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">72,987,956</td>
	</tr><tr class="dataTDRight" style="background-color:#EFEFEF;">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2006</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">7</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">60,838,606</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">14,912,621</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">75,751,227</td>
	</tr><tr class="dataTDRight">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2006</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">8</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">58,303,233</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">14,171,796</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">72,475,029</td>
	</tr><tr class="dataTDRight" style="background-color:#EFEFEF;">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2006</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">9</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">49,949,551</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">12,010,922</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">61,960,473</td>
	</tr><tr class="dataTDRight">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2006</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">10</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">55,088,986</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">11,517,228</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">66,606,214</td>
	</tr><tr class="dataTDRight" style="background-color:#EFEFEF;">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2006</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">11</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">53,852,209</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">11,222,687</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">65,074,896</td>
	</tr><tr class="dataTDRight">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2006</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">12</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">53,538,970</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">12,385,958</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">65,924,928</td>
	</tr><tr class="dataTDRight" style="background-color:LightYellow;">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;"><B>2006</B></td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;"><B>TOTAL</B></td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;"><B>658,362,620</B></td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;"><B>149,740,591</B></td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;"><B>808,103,211</B></td>
	</tr><tr class="dataTDRight">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2007</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">1</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">50,022,168</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">12,072,442</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">62,094,610</td>
	</tr><tr class="dataTDRight" style="background-color:#EFEFEF;">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2007</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">47,766,421</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">10,591,580</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">58,358,001</td>
	</tr><tr class="dataTDRight">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2007</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">3</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">59,244,232</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">13,247,375</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">72,491,607</td>
	</tr><tr class="dataTDRight" style="background-color:#EFEFEF;">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2007</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">4</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">57,398,267</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">12,795,517</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">70,193,784</td>
	</tr><tr class="dataTDRight">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2007</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">5</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">59,285,571</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">12,972,589</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">72,258,160</td>
	</tr><tr class="dataTDRight" style="background-color:#EFEFEF;">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2007</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">6</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">61,493,934</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">14,170,877</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">75,664,811</td>
	</tr><tr class="dataTDRight">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2007</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">7</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">63,457,403</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">15,470,687</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">78,928,090</td>
	</tr><tr class="dataTDRight" style="background-color:#EFEFEF;">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2007</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">8</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">62,660,179</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">15,131,296</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">77,791,475</td>
	</tr><tr class="dataTDRight">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2007</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">9</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">52,310,402</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">12,332,434</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">64,642,836</td>
	</tr><tr class="dataTDRight" style="background-color:#EFEFEF;">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2007</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">10</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">57,208,618</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">12,392,938</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">69,601,556</td>
	</tr><tr class="dataTDRight">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2007</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">11</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">55,047,116</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">12,023,481</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">67,070,597</td>
	</tr><tr class="dataTDRight" style="background-color:#EFEFEF;">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2007</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">12</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">53,291,139</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">13,123,756</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">66,414,895</td>
	</tr><tr class="dataTDRight" style="background-color:LightYellow;">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;"><B>2007</B></td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;"><B>TOTAL</B></td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;"><B>679,185,450</B></td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;"><B>156,324,972</B></td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;"><B>835,510,422</B></td>
	</tr><tr class="dataTDRight" style="background-color:#EFEFEF;">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2008</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">1</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">50,245,100</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">12,794,514</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">63,039,614</td>
	</tr><tr class="dataTDRight">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2008</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">50,118,363</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">11,677,400</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">61,795,763</td>
	</tr><tr class="dataTDRight" style="background-color:#EFEFEF;">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2008</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">3</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">59,213,077</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">14,221,964</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">73,435,041</td>
	</tr><tr class="dataTDRight">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2008</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">4</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">55,611,053</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">12,983,854</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">68,594,907</td>
	</tr><tr class="dataTDRight" style="background-color:#EFEFEF;">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2008</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">5</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">58,047,400</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">13,628,619</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">71,676,019</td>
	</tr><tr class="dataTDRight">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2008</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">6</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">59,559,171</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">14,447,504</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">74,006,675</td>
	</tr><tr class="dataTDRight" style="background-color:#EFEFEF;">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2008</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">7</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">61,401,480</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">15,488,628</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">76,890,108</td>
	</tr><tr class="dataTDRight">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2008</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">8</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">58,966,473</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">15,369,492</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">74,335,965</td>
	</tr><tr class="dataTDRight" style="background-color:#EFEFEF;">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2008</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">9</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">47,680,101</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">11,759,694</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">59,439,795</td>
	</tr><tr class="dataTDRight">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2008</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">10</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">52,956,023</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">11,952,515</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">64,908,538</td>
	</tr><tr class="dataTDRight" style="background-color:#EFEFEF;">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2008</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">11</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">47,658,141</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">11,288,311</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">58,946,452</td>
	</tr><tr class="dataTDRight">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2008</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">12</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">50,253,800</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">12,499,216</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">62,753,016</td>
	</tr><tr class="dataTDRight" style="background-color:LightYellow;">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;"><B>2008</B></td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;"><B>TOTAL</B></td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;"><B>651,710,182</B></td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;"><B>158,111,711</B></td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;"><B>809,821,893</B></td>
	</tr><tr class="dataTDRight">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2009</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">1</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">44,825,056</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">12,075,267</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">56,900,323</td>
	</tr><tr class="dataTDRight" style="background-color:#EFEFEF;">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2009</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">43,680,328</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">10,412,676</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">54,093,004</td>
	</tr><tr class="dataTDRight">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2009</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">3</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">53,534,891</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">12,508,793</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">66,043,684</td>
	</tr><tr class="dataTDRight" style="background-color:#EFEFEF;">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2009</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">4</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">52,247,781</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">12,629,805</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">64,877,586</td>
	</tr><tr class="dataTDRight">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2009</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">5</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">52,951,246</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">11,806,548</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">64,757,794</td>
	</tr><tr class="dataTDRight" style="background-color:#EFEFEF;">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2009</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">6</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">55,898,027</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">13,199,636</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">69,097,663</td>
	</tr><tr class="dataTDRight">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2009</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">7</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">59,468,957</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">14,953,615</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">74,422,572</td>
	</tr><tr class="dataTDRight" style="background-color:#EFEFEF;">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2009</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">8</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">56,568,180</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">14,844,821</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">71,413,001</td>
	</tr><tr class="dataTDRight">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2009</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">9</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">48,235,025</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">11,659,775</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">59,894,800</td>
	</tr><tr class="dataTDRight" style="background-color:#EFEFEF;">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2009</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">10</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">52,279,405</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">11,905,529</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">64,184,934</td>
	</tr><tr class="dataTDRight">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2009</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">11</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">48,584,832</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">11,093,714</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">59,678,546</td>
	</tr><tr class="dataTDRight" style="background-color:#EFEFEF;">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2009</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">12</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">49,793,527</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">12,659,154</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">62,452,681</td>
	</tr><tr class="dataTDRight" style="background-color:LightYellow;">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;"><B>2009</B></td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;"><B>TOTAL</B></td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;"><B>618,067,255</B></td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;"><B>149,749,333</B></td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;"><B>767,816,588</B></td>
	</tr><tr class="dataTDRight" style="background-color:#EFEFEF;">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2010</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">1</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">45,501,620</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">12,393,439</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">57,895,059</td>
	</tr><tr class="dataTDRight">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2010</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">42,440,614</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">10,694,165</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">53,134,779</td>
	</tr><tr class="dataTDRight" style="background-color:#EFEFEF;">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2010</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">3</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">54,424,077</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">13,279,320</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">67,703,397</td>
	</tr><tr class="dataTDRight">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2010</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">4</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">52,498,074</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">12,398,700</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">64,896,774</td>
	</tr><tr class="dataTDRight" style="background-color:#EFEFEF;">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2010</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">5</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">53,842,422</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">13,380,664</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">67,223,086</td>
	</tr><tr class="dataTDRight">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2010</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">6</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">56,689,853</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">14,406,776</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">71,096,629</td>
	</tr><tr class="dataTDRight" style="background-color:#EFEFEF;">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2010</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">7</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">59,142,493</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">16,026,852</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">75,169,345</td>
	</tr><tr class="dataTDRight">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2010</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">8</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">57,370,748</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">15,317,926</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">72,688,674</td>
	</tr><tr class="dataTDRight" style="background-color:#EFEFEF;">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2010</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">9</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">50,304,708</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">12,599,149</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">62,903,857</td>
	</tr><tr class="dataTDRight">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2010</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">10</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">54,826,050</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">12,874,707</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">67,700,757</td>
	</tr><tr class="dataTDRight" style="background-color:#EFEFEF;">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2010</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">11</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">51,420,519</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">11,651,314</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">63,071,833</td>
	</tr><tr class="dataTDRight">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2010</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">12</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">51,076,415</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">12,917,451</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">63,993,866</td>
	</tr><tr class="dataTDRight" style="background-color:LightYellow;">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;"><B>2010</B></td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;"><B>TOTAL</B></td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;"><B>629,537,593</B></td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;"><B>157,940,463</B></td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;"><B>787,478,056</B></td>
	</tr><tr class="dataTDRight">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2011</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">1</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">46,305,000</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">12,668,763</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">58,973,763</td>
	</tr><tr class="dataTDRight" style="background-color:#EFEFEF;">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2011</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">43,657,818</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">10,944,610</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">54,602,428</td>
	</tr><tr class="dataTDRight">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2011</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">3</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">55,649,428</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">13,473,705</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">69,123,133</td>
	</tr><tr class="dataTDRight" style="background-color:#EFEFEF;">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2011</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">4</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">52,858,479</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">13,537,152</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">66,395,631</td>
	</tr><tr class="dataTDRight">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2011</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">5</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">55,982,234</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">13,935,132</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">69,917,366</td>
	</tr><tr class="dataTDRight" style="background-color:#EFEFEF;">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2011</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">6</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">57,778,699</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">14,814,672</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">72,593,371</td>
	</tr><tr class="dataTDRight">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2011</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">7</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">60,310,568</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">16,623,674</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">76,934,242</td>
	</tr><tr class="dataTDRight" style="background-color:#EFEFEF;">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2011</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">8</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">57,403,835</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">15,753,438</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">73,157,273</td>
	</tr><tr class="dataTDRight">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2011</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">9</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">50,982,170</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">13,220,884</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">64,203,054</td>
	</tr><tr class="dataTDRight" style="background-color:#EFEFEF;">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2011</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">10</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">54,124,363</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">13,199,913</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">67,324,276</td>
	</tr><tr class="dataTDRight">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2011</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">11</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">51,660,083</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">12,156,133</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">63,816,216</td>
	</tr><tr class="dataTDRight" style="background-color:#EFEFEF;">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2011</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">12</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">51,534,990</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">13,559,050</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">65,094,040</td>
	</tr><tr class="dataTDRight" style="background-color:LightYellow;">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;"><B>2011</B></td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;"><B>TOTAL</B></td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;"><B>638,247,667</B></td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;"><B>163,887,126</B></td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;"><B>802,134,793</B></td>
	</tr><tr class="dataTDRight" style="background-color:#EFEFEF;">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2012</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">1</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">47,080,840</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">13,206,801</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">60,287,641</td>
	</tr><tr class="dataTDRight">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2012</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">46,405,385</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">11,732,944</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">58,138,329</td>
	</tr><tr class="dataTDRight" style="background-color:#EFEFEF;">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2012</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">3</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">56,200,391</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">14,387,677</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">70,588,068</td>
	</tr><tr class="dataTDRight">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2012</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">4</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">53,691,570</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">13,995,377</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">67,686,947</td>
	</tr><tr class="dataTDRight" style="background-color:#EFEFEF;">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2012</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">5</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">55,749,349</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">14,291,285</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">70,040,634</td>
	</tr><tr class="dataTDRight">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2012</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">6</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">57,903,293</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">15,582,335</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">73,485,628</td>
	</tr><tr class="dataTDRight" style="background-color:#EFEFEF;">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2012</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">7</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">59,688,267</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">16,969,590</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">76,657,857</td>
	</tr><tr class="dataTDRight">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2012</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">8</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">58,646,304</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">16,616,643</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">75,262,947</td>
	</tr><tr class="dataTDRight" style="background-color:#EFEFEF;">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2012</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">9</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">50,134,504</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">13,783,049</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">63,917,553</td>
	</tr><tr class="dataTDRight">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2012</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">10</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">53,779,646</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">13,386,771</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">67,166,417</td>
	</tr><tr class="dataTDRight" style="background-color:#EFEFEF;">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2012</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">11</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">51,844,482</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">12,749,617</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">64,594,099</td>
	</tr><tr class="dataTDRight">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2012</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">12</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">51,165,451</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">14,079,411</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">65,244,862</td>
	</tr><tr class="dataTDRight" style="background-color:LightYellow;">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;"><B>2012</B></td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;"><B>TOTAL</B></td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;"><B>642,289,482</B></td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;"><B>170,781,500</B></td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;"><B>813,070,982</B></td>
	</tr><tr class="dataTDRight">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2013</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">1</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">47,816,859</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">13,768,819</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">61,585,678</td>
	</tr><tr class="dataTDRight" style="background-color:#EFEFEF;">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2013</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">45,740,158</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">12,037,584</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">57,777,742</td>
	</tr><tr class="dataTDRight">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2013</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">3</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">56,564,538</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">15,188,333</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">71,752,871</td>
	</tr><tr class="dataTDRight" style="background-color:#EFEFEF;">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2013</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">4</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">53,228,575</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">14,301,619</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">67,530,194</td>
	</tr><tr class="dataTDRight">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2013</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">5</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">56,562,929</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">15,353,665</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">71,916,594</td>
	</tr><tr class="dataTDRight" style="background-color:#EFEFEF;">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2013</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">6</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">57,990,789</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">16,403,199</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">74,393,988</td>
	</tr><tr class="dataTDRight">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2013</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">7</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">59,310,478</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">17,748,869</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">77,059,347</td>
	</tr><tr class="dataTDRight" style="background-color:#EFEFEF;">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2013</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">8</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">58,115,405</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">17,666,442</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">75,781,847</td>
	</tr><tr class="dataTDRight">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2013</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">9</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">50,766,098</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">14,256,736</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">65,022,834</td>
	</tr><tr class="dataTDRight" style="background-color:#EFEFEF;">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2013</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">10</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">54,706,246</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">14,341,721</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">69,047,967</td>
	</tr><tr class="dataTDRight">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2013</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">11</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">50,542,543</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">13,167,243</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">63,709,786</td>
	</tr><tr class="dataTDRight" style="background-color:#EFEFEF;">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2013</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">12</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">54,332,936</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">15,095,548</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">69,428,484</td>
	</tr><tr class="dataTDRight" style="background-color:LightYellow;">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;"><B>2013</B></td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;"><B>TOTAL</B></td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;"><B>645,677,554</B></td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;"><B>179,329,778</B></td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;"><B>825,007,332</B></td>
	</tr><tr class="dataTDRight" style="background-color:#EFEFEF;">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2014</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">1</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">47,957,371</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">14,692,606</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">62,649,977</td>
	</tr><tr class="dataTDRight">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2014</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">45,513,184</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">12,482,600</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">57,995,784</td>
	</tr><tr class="dataTDRight" style="background-color:#EFEFEF;">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2014</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">3</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">57,762,170</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">15,604,456</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">73,366,626</td>
	</tr><tr class="dataTDRight">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2014</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">4</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">55,247,482</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">15,471,267</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">70,718,749</td>
	</tr><tr class="dataTDRight" style="background-color:#EFEFEF;">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2014</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">5</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">57,888,637</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">16,250,696</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">74,139,333</td>
	</tr><tr class="dataTDRight">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2014</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">6</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">59,262,095</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">17,284,507</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">76,546,602</td>
	</tr><tr class="dataTDRight" style="background-color:#EFEFEF;">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2014</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">7</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">61,757,698</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">18,783,071</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">80,540,769</td>
	</tr><tr class="dataTDRight">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2014</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">8</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">59,758,814</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">18,685,066</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">78,443,880</td>
	</tr><tr class="dataTDRight" style="background-color:#EFEFEF;">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2014</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">9</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">52,529,472</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">14,971,740</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">67,501,212</td>
	</tr><tr class="dataTDRight">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2014</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">10</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">57,084,923</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">14,968,236</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">72,053,159</td>
	</tr><tr class="dataTDRight" style="background-color:#EFEFEF;">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2014</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">11</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">52,578,037</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">13,730,768</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">66,308,805</td>
	</tr><tr class="dataTDRight">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2014</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">12</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">55,487,072</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">15,805,756</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">71,292,828</td>
	</tr><tr class="dataTDRight" style="background-color:LightYellow;">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;"><B>2014</B></td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;"><B>TOTAL</B></td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;"><B>662,826,955</B></td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;"><B>188,730,769</B></td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;"><B>851,557,724</B></td>
	</tr><tr class="dataTDRight">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2015</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">1</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">49,727,992</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">15,466,269</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">65,194,261</td>
	</tr><tr class="dataTDRight" style="background-color:#EFEFEF;">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2015</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">47,164,898</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">13,325,293</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">60,490,191</td>
	</tr><tr class="dataTDRight">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2015</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">3</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">59,557,626</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">16,338,496</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">75,896,122</td>
	</tr><tr class="dataTDRight" style="background-color:#EFEFEF;">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2015</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">4</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">57,698,342</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">16,024,819</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">73,723,161</td>
	</tr><tr class="dataTDRight">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2015</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">5</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">60,252,607</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">17,115,194</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">77,367,801</td>
	</tr><tr class="dataTDRight" style="background-color:#EFEFEF;">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2015</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">6</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">61,811,276</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">18,203,199</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">80,014,475</td>
	</tr><tr class="dataTDRight">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2015</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">7</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">65,129,348</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">20,215,002</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">85,344,350</td>
	</tr><tr class="dataTDRight" style="background-color:#EFEFEF;">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2015</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">8</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">62,770,806</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">19,914,264</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">82,685,070</td>
	</tr><tr class="dataTDRight">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2015</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">9</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">55,989,599</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">16,111,956</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">72,101,555</td>
	</tr><tr class="dataTDRight" style="background-color:#EFEFEF;">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2015</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">10</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">60,892,617</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">16,188,843</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">77,081,460</td>
	</tr><tr class="dataTDRight">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2015</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">11</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">57,150,828</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">14,838,103</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">71,988,931</td>
	</tr><tr class="dataTDRight" style="background-color:#EFEFEF;">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2015</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">12</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">57,870,955</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">16,843,180</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">74,714,135</td>
	</tr><tr class="dataTDRight" style="background-color:LightYellow;">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;"><B>2015</B></td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;"><B>TOTAL</B></td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;"><B>696,016,894</B></td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;"><B>200,584,618</B></td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;"><B>896,601,512</B></td>
	</tr><tr class="dataTDRight" style="background-color:#EFEFEF;">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2016</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">1</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">52,474,897</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">16,325,720</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">68,800,617</td>
	</tr><tr class="dataTDRight">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2016</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">51,109,273</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">14,198,168</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">65,307,441</td>
	</tr><tr class="dataTDRight" style="background-color:#EFEFEF;">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2016</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">3</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">61,594,107</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">17,212,271</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">78,806,378</td>
	</tr><tr class="dataTDRight">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2016</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">4</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">58,887,024</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">16,421,406</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">75,308,430</td>
	</tr><tr class="dataTDRight" style="background-color:#EFEFEF;">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2016</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">5</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">62,754,540</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">17,641,152</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">80,395,692</td>
	</tr><tr class="dataTDRight">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2016</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">6</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">64,760,254</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">19,171,221</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">83,931,475</td>
	</tr><tr class="dataTDRight" style="background-color:#EFEFEF;">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2016</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">7</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">66,133,909</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">20,823,540</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">86,957,449</td>
	</tr><tr class="dataTDRight">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">2016</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">8</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">63,477,187</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">19,976,367</td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;">83,453,554</td>
	</tr><tr class="dataTDRight" style="background-color:LightYellow;">
		<td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;"><B>2016</B></td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;"><B>TOTAL</B></td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;"><B>481,191,191</B></td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;"><B>141,769,845</B></td><td style="font-family: Verdana, Geneva, Arial, Helvetica, sans-serif;"><B>622,961,036</B></td>
	</tr>
</table><BR>Note: All numbers are for scheduled services.<BR><BR>SOURCE: Bureau of Transportation Statistics T-100 Market data.